### ISSUE TITLE
大佬，国内用小火箭能不能加一个打开小火箭能刷国内的抖音，感谢大佬，现在刷不了

### ISSUE THREAD

**Issue by peyxbxhdjcb** [wwg135/Shadowrocket#1]

**Comment by wwg135** [comment]
已修改，麻烦再试一下！！








------------------ 原始邮件 ------------------


    


        发件人: peyxbxhdjcb  ***@***.***>    






    


        发送时间: 2022-08-28 00:55:02    






    


        收件人: wwg135/Shadowrocket  ***@***.***>     






    


        抄送: Subscribed  ***@***.***>     






    


        主题: [wwg135/Shadowrocket] 大佬，国内用小火箭能不能加一个打开小火箭能刷国内的抖音，感谢大佬，现在刷不了 (Issue #1)

**Comment by peyxbxhdjcb** [comment]
谢谢大佬，可以了

**Comment by peyxbxhdjcb** [comment]
大老，好像又用不了了，在退出来就又不行了
