### ISSUE TITLE
大佬，小火箭里面改了抖音用了一次，退出来在进就不行了，油管现在也加载不出来

### ISSUE THREAD

**Issue by peyxbxhdjcb** [wwg135/Shadowrocket#2]

**Comment by wwg135** [comment]
抖音我试了没问题的喔，油管没有自己，删除一下油管的广告拦截











------------------ 原始邮件 ------------------


    


        发件人: peyxbxhdjcb  ***@***.***>    






    


        发送时间: 2022-08-28 09:06:47    






    


        收件人: wwg135/Shadowrocket  ***@***.***>     






    


        抄送: Subscribed  ***@***.***>     






    


        主题: [wwg135/Shadowrocket] 大佬，小火箭里面改了抖音用了一次，退出来在进就不行了，油管现在也加载不出来 (Issue #2)

**Comment by wwg135** [comment]
我这边没使用油管的











------------------ 原始邮件 ------------------


    


        发件人: peyxbxhdjcb  ***@***.***>    






    


        发送时间: 2022-08-28 09:06:47    






    


        收件人: wwg135/Shadowrocket  ***@***.***>     






    


        抄送: Subscribed  ***@***.***>     






    


        主题: [wwg135/Shadowrocket] 大佬，小火箭里面改了抖音用了一次，退出来在进就不行了，油管现在也加载不出来 (Issue #2)

**Comment by wwg135** [comment]
你更新配置？？还是自己修改里面？？








------------------ 原始邮件 ------------------


    


        发件人: peyxbxhdjcb  ***@***.***>    






    


        发送时间: 2022-08-28 12:20:49    






    


        收件人: wwg135/Shadowrocket  ***@***.***>     






    


        抄送: wwg135  ***@***.***>,Comment  ***@***.***>     






    


        主题: Re: [wwg135/Shadowrocket] 大佬，小火箭里面改了抖音用了一次，退出来在进就不行了，油管现在也加载不出来 (Issue #2)    

 

Closed #2 as completed.
